name: Webapp

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - "apps/picosafe-webapp/**"
      - "packages/picosafe/**"
      - ".github/workflows/webapp.yml"

jobs:
  build:
    name: Build Webapp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build webapp
        run: npm run build:webapp

      - name: Type check webapp
        run: npm run typecheck -w picosafe-webapp

  code-quality:
    name: Code Quality (Webapp)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check code quality with Biome
        run: npm run check -w picosafe-webapp

  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
        working-directory: apps/picosafe-webapp

      - name: Run E2E tests
        run: npm run test:e2e -w picosafe-webapp

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: apps/picosafe-webapp/playwright-report/
          retention-days: 30
